chore: fix secrets in docker history

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -50,17 +50,46 @@ add_testrepo_commit() {
     cd .. || error_exit "error when committing changes"
 }
 
+validate_docker_version() {
+    SERVER_VERSION=$(docker version -f "{{.Server.Version}}")
+    SERVER_VERSION_MAJOR=$(echo "$SERVER_VERSION"| cut -d'.' -f 1)
+    SERVER_VERSION_MINOR=$(echo "$SERVER_VERSION"| cut -d'.' -f 2)
+    SERVER_VERSION_BUILD=$(echo "$SERVER_VERSION"| cut -d'.' -f 3)
+
+    if [ "${SERVER_VERSION_MAJOR}" -ge 20 ] && \
+    [ "${SERVER_VERSION_MINOR}" -ge 10 ]  && \
+    [ "${SERVER_VERSION_BUILD}" -ge 0 ]; then
+        echo "Docker version >= 20.10 it's ok"
+    else
+        echo "Docker version less than 20.10 can't continue"
+        exit 1
+    fi
+}
+
+scan_secrets_in_docker_history() {
+    output_info "Checking for vulnerabilities"
+    if docker history --no-trunc ambimax/semantic-release:latest | grep "${GITHUB_TOKEN}"; then
+        error_exit "Content of \$GITHUB_TOKEN found in history!!!!!"
+    else
+        output_info "No GITHUB_TOKEN found in history"
+    fi
+}
+
 ############################################################################################
 # Validate
 ############################################################################################
 [ -n "$GITHUB_TOKEN" ] || error_exit "\$GITHUB_TOKEN must be set"
 
+validate_docker_version
+
 
 ############################################################################################
 # Build docker image
 ############################################################################################
-docker build --build-arg GITHUB_TOKEN -t ambimax/semantic-release:latest .
+export DOCKER_BUILDKIT=1
+docker build --secret id=GITHUB_TOKEN -t ambimax/semantic-release:latest .
 
+scan_secrets_in_docker_history
 
 ############################################################################################
 # Prepare testrepo
